### 1. Kiểm tra sức khỏe API Server (Health Check)
GET http://127.0.0.1:8000/health
Accept: application/json


### 2. Trích xuất mã OTP từ dòng tài khoản (Chế độ Giả lập Mock)
POST http://127.0.0.1:8000/api/get-code
Content-Type: application/json

{
  "account_str": "demo_user@outlook.com|DemoPassword123|M.C_SAMPLE_REFRESH_TOKEN|9e5f94bc-e8a4-4e73-b8be-63364c29d753",
  "keyword": "mã xác nhận",
  "use_mock": true
}


### 3. Trích xuất mã OTP từ hòm thư Outlook thật (Chế độ Thực tế)
POST http://127.0.0.1:8000/api/get-code
Content-Type: application/json

{
  "account_str": "your_email@outlook.com|your_password|your_refresh_token|9e5f94bc-e8a4-4e73-b8be-63364c29d753",
  "keyword": null,
  "use_mock": false
}
