### 1. Kiểm tra sức khỏe API Server (Health Check)
GET http://127.0.0.1:8000/health
Accept: application/json


### 2. Trích xuất mã OTP từ dòng tài khoản (Chế độ Giả lập Mock)
POST http://127.0.0.1:8000/api/get-code
Content-Type: application/json

{
  "account_str": "demo_user@outlook.com|DemoPassword123|M.C_SAMPLE_REFRESH_TOKEN|9e5f94bc-e8a4-4e73-b8be-63364c29d753",
  "keyword": "mã xác nhận",
  "use_mock": true
}


### 3. Endpoint mới (GET): Lấy mã OTP chỉ bằng Query Param Email
GET http://127.0.0.1:8000/api/get-code-by-email?email=sylvesterrojas997795@outlook.com
Accept: application/json


### 4. Endpoint mới (POST): Lấy mã OTP chỉ bằng Body JSON Email
POST http://127.0.0.1:8000/api/get-code-by-email
Content-Type: application/json

{
  "email": "sylvesterrojas997795@outlook.com"
}


### 5. Quản lý danh sách tài khoản đã lưu trong SQLite DB
GET http://127.0.0.1:8000/api/accounts
Accept: application/json
